# Ruff configuration for PS2MapState project

# Target Python version
target-version = "py313"

# Line length
line-length = 100

# Exclude some directories
exclude = [
    ".git",
    ".venv",
    "node_modules",
    "__pycache__",
    ".idea",
]

[lint]
# Enable all rules by default
select = ["ALL"]

# Allow unused variables when underscore-prefixed
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Ignore specific rules that might be too strict
ignore = [
    "D203", # one-blank-line-before-class (conflicts with D211)
    "D212", # multi-line-summary-first-line (conflicts with D213)
    "PLR2004", # Magic value used in comparison
    "PTH123", # `open()` should be replaced by `Path.open()`
    "INP001", # Implicit namespace package
]

[lint.per-file-ignores]
# Ignore specific rules in test files
"tests/**/*.py" = [
    "S101", # Use of assert detected
    "D100", # Missing docstring in public module
    "D103", # Missing docstring in public function
    "ANN201", # Missing return type annotation for public function
]
